name: Executar Algoritmo Genetico TSP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite que você clique em um botão no site para rodar manualmente

jobs:
  executar-ia:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o codigo do repositorio
      uses: actions/checkout@v4

    - name: Compilar o codigo em C
      # Lembre-se de trocar "seu_codigo.c" pelo nome exato do seu arquivo
      run: gcc Exemplo Modelo.c -o evolucao -lm

    - name: Executar a Evolucao do TSP
      run: ./evolucao
