name: Executar Algoritmo Genetico TSP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  executar-ia:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o codigo do repositorio
      uses: actions/checkout@v4

    - name: Entrar na pasta, Compilar e Executar
      run: |
        cd "Exercicios/Exercicios TSP 2 - 4000 Postes"
        gcc CodTSP.c -o evolucao -lm
        ./evolucao
